name: Continuous Integration

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Log in Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
        

      - name: Build Eureka Naming Server Container Image
        working-directory: ./Dockerizing/10-naming-server
        run: mvn spring-boot:build-image -DskipTests   

      - name: Build API Gateway Server Container Image
        working-directory: ./Dockerizing/10-api-gateway
        run: mvn spring-boot:build-image -DskipTests 

      - name: Build Cambio Service Server Container Image
        working-directory: ./Dockerizing/10-cambio-service
        run: mvn clean package -DskipTests

      - name: Build Book Service Server Container Image
        working-directory: ./Dockerizing/10-book-service
        run: mvn clean package -DskipTests

      - name: Dcoker Compose build
        working-directory: ./Dockerizing/
        run: docker-compose build  

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/naming-server:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/naming-server:${{github.run_id}}
      
   
